<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
    <PackageReference Include="BlazorPro.Spinkit" Version="1.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="9.0.15" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.15" />
    <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="9.0.15" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.15" />
    <PackageReference Include="Serilog" Version="4.2.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\NexusUserTest.Common\NexusUserTest.Common.csproj" />
  </ItemGroup>

</Project>
